# Usar una imagen base de Python
FROM python:3.11

# Establecer el directorio de trabajo
WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copiar el código fuente del backend y el script de entrada
COPY . .
COPY entrypoint.sh /usr/local/bin/


CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
EXPOSE 8000
